id: P77AF7DB4
initial_creation_type: input
source_metadata:
  title: Śāriputras biographies of Virupa, Goraknātha and Golenāthā
  author: པཎ་ཆེན་ཤཱ་རི་པུ་ཏྲ།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2021-07-06);
    revision in process, no thematic TEI markup; abbreviated orthographic forms spelled
    out throughout the text'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Google Docs, OCR-processed (Tesseract)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/5191
  bases:
    731d:
      title: Śāriputras biographies of Virupa, Goraknātha and Golenāthā
      order: 1
      base_file: 731d.txt
created_at: '2022-04-15T18:27:48.113522'
last_modified_at: '2022-04-15T18:27:48.113530'
quality: null
